config/routes.rb
Rails.application.routes.draw do
  resource :user
  resources :posts
  resources :likes

  root "users#new"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :create_user

  private

  def current_user
    @current_user = User.where(id: cookies[:user_id]).last
  end

  def create_user
    redirect_to "/" unless current_user.present?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    Like.create(user: current_user, post: post)

    redirect_back fallback_location: root_path
  end

  def destroy
    Like.find(params[:id]).destroy

    redirect_back fallback_location: root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user_name = current_user.name
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :create_user, only: [:new, :create]

  def new
    redirect_to "/posts" if current_user.present?
  end

  def create
    cookies[:user_id] = User.create(name: params[:name]).id unless current_user.present?

    redirect_to "/posts"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_for_post(post)
    Like.where(user_id: @current_user.id, post_id: post.id).last
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 text-uppercase">hello! <%= @user_name %></h1>
        <h4 class="text-white-50 mx-auto mt-2 mb-5">
        <% @posts.each do |post| %>
        <%= truncate(post.body) %> <%= link_to("see more", post) %>
  <p>
  <% if like_for_post(post) %>
    <%= link_to "Unlike", like_path(like_for_post(post)), method: :delete %>
  <% else %>
    <%= link_to "Like", likes_path(post_id: post.id), method: :post %>
  <% end %>
</p>
<% end %>
        </h4>
        
      </div>
    </div>
  </header>

app/views/posts/show.html.erb
<header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 text-uppercase"><%= @post.body %></h1>
        <h2 class="text-white-50 mx-auto mt-2 mb-5"><%= link_to "All posts", "/posts" %></h2>
      </div>
    </div>
  </header>

app/views/users/new.html.erb
 <header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 text-uppercase">Welcome to the blog.</h1>
        <h2 class="text-white-50 mx-auto mt-2 mb-5"> Please enter your name to continue.</h2>
        <%= form_with(url: "/user", method: "post") do %>
        <%= label_tag(:name, "Name:") %>
        <%= text_field_tag(:name) %>
        <%= submit_tag("Submit") %>
        <% end %>
      </div>
    </div>
  </header>